# Generated by Django 6.1 on 2026-08-17 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('tardanza_min', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('entrada_sin_salida', 'Entrada sin salida'), ('corregido', 'Corregido')], default='entrada_sin_salida', max_length=20)),
            ],
            options={
                'ordering': ['-fecha', 'pasante'],
            },
        ),
        migrations.CreateModel(
            name='Correccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to=settings.AUTH_USER_MODEL)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='registro.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pasante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('area', models.CharField(max_length=80)),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='pasante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='registro.pasante'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('pasante', 'fecha')},
        ),
    ]
