# Generated by Django 6.1 on 2026-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado (no se cuenta tardanza)'), ('horario_especial', 'Horario especial (otra hora de entrada ese día)')], max_length=20)),
                ('hora_entrada_especial', models.TimeField(blank=True, help_text='Solo para horario especial: hora de entrada esperada ese día.', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
