# Generated by Django 6.1 on 2026-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_diaespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Institución', max_length=120)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('radio_metros', models.PositiveIntegerField(default=100, help_text='Distancia máxima (en metros) desde el punto para poder marcar.')),
            ],
            options={
                'verbose_name': 'Ubicación de la institución',
                'verbose_name_plural': 'Ubicación de la institución',
            },
        ),
    ]
