# Generated by Django 6.1 on 2026-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='lat_entrada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='lat_salida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='lng_entrada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='lng_salida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
