# Generated by Django 6.1 on 2026-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_asistencia_lat_entrada_asistencia_lat_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasante',
            name='dispositivo_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
