# Generated by Django 6.1 on 2026-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_loginsecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('nivel_bloqueo', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
